### ISSUE TITLE
Add a way to configure the Snipcart version

### ISSUE THREAD

**Issue by couellet** [hotdoy/grav-theme-wheat#101]
At the moment, the version of Snipcart is hardcoded, it could be nice to make it configurable, however, since the Snipcart team can change the markup / CSS classes, it might causes some issues with your cart customization.

Feel free to dismiss this issue if you prefer the keep the control on the version used by this theme.

**Comment by hotdoy** [comment]
The theme is aimed at developers so they should be able to take ownership and change it as they see fit. BUT I think it's a nice idea for testing or hotfixes. 
I'll add a `snipcart version overwrite` in the theme settings in the upcoming v0.9.2
Thanks!

**Comment by hotdoy** [comment]
Done 😃
