### ISSUE TITLE
[Snipcart] Add support for multi currency

### ISSUE THREAD

**Issue by couellet** [hotdoy/grav-theme-wheat#102]
Snipcart has a multi-currency feature, it could be nice to support it in the theme. It's something that is used quite a lot, and lots of users are having troubles implementing it when they're not very tech-saavy.

Documentation available [here](https://docs.snipcart.com/v3/setup/multi-currency).

**Comment by hotdoy** [comment]
I've been pushing this one forward for a while now but with dialog and modals out of the way with 0.9.1 I guess it's about time I take a look at it.
