### ISSUE TITLE
[Snipcart] Add support for all product attributes

### ISSUE THREAD

**Issue by couellet** [hotdoy/grav-theme-wheat#98]
Some data attributes are not configurable, some examples: `data-item-max-quantity`, `data-item-taxes`, `data-item-taxable`, `data-item-shippable`.

It would be nice to review [this section](https://docs.snipcart.com/v3/setup/products) and add missing attributes.

**Comment by hotdoy** [comment]
I'm with you. I'm long overdue for a pass on the product blueprint in general. 
I'll add the booleans in v0.9.3 and progressively add the more complex ones.

**Comment by hotdoy** [comment]
`data-item-taxable` and `data-item-shippable` where added in repo.
